version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d urlshortener"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  ui:
    working_dir: /app
    image: node:20-alpine
    command: sh -c "npm i && npm run dev -- --host"
    ports:
      - "3001:5173"
    volumes:
      - ./frontend:/app
    environment:
      - ./frontend/.env
    depends_on:
      - api

volumes:
  dbdata: